apiVersion: v1
kind: Secret
metadata:
  name: tee-time-agent-secrets
  labels:
    app: tee-time-agent
type: Opaque
stringData:
  TEE_AGENT_BRS_USERNAME: "<username>"
  TEE_AGENT_BRS_PASSWORD: "<password>"
  TEE_AGENT_CLUB_SLUG: "aylesburyvale"
  TEE_AGENT_COURSE_ID: "1"
  TEE_AGENT_TELEGRAM_BOT_TOKEN: "<telegram_bot_token>"
  TEE_AGENT_TELEGRAM_CHAT_ID: "<telegram_chat_id>"
  TEE_AGENT_OLLAMA_BASE_URL: "http://ollama.ollama.svc.cluster.local:11434"
  TEE_AGENT_OLLAMA_MODEL: "gemma3:12b"
