apiVersion: v1
kind: Namespace
metadata:
  name: edulink-agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edulink-agent
  namespace: edulink-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edulink-agent
  template:
    metadata:
      labels:
        app: edulink-agent
    spec:
      containers:
        - name: edulink-agent
          image: ghcr.io/your-org/edulink-agent:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: edulink-agent-secrets
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: edulink-agent
  namespace: edulink-agent
spec:
  selector:
    app: edulink-agent
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
